/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Comment = IDL.Record({ 'text' : IDL.Text, 'author' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Record({ 'provider' : IDL.Text }),
  'creditCard' : IDL.Null,
  'digitalWallet' : IDL.Record({ 'provider' : IDL.Text }),
  'debitCard' : IDL.Null,
  'netBanking' : IDL.Record({ 'bank' : IDL.Text }),
});
export const Time = IDL.Int;
export const PaymentTransaction = IDL.Record({
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'failureReason' : IDL.Opt(IDL.Text),
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const StoryContentType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'contentType' : StoryContentType,
  'file' : ExternalBlob,
  'uploadTime' : Time,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'attachments' : IDL.Opt(IDL.Vec(ExternalBlob)),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'uploadTime' : Time,
});
export const FriendRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PushSubscription = IDL.Record({
  'endpoint' : IDL.Text,
  'p256dhKey' : IDL.Text,
  'authKey' : IDL.Text,
});
export const ReelStats = IDL.Record({
  'shares' : IDL.Nat,
  'views' : IDL.Nat,
  'likes' : IDL.Nat,
  'comments' : IDL.Vec(Comment),
  'dislikes' : IDL.Nat,
});
export const SignalingEntryPublic = IDL.Record({
  'data' : IDL.Text,
  'sender' : IDL.Principal,
  'dataType' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const NotificationType = IDL.Variant({
  'paymentNotification' : IDL.Null,
  'videoCall' : IDL.Null,
  'friendRequestAccepted' : IDL.Null,
  'newMessage' : IDL.Null,
  'friendRequest' : IDL.Null,
});
export const Notification = IDL.Record({
  'content' : IDL.Text,
  'notificationType' : NotificationType,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'senderName' : IDL.Text,
});
export const FriendRequest = IDL.Record({
  'status' : FriendRequestStatus,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
});
export const SearchUsersResult = IDL.Record({
  'pendingRequests' : IDL.Vec(FriendRequest),
  'friends' : IDL.Vec(IDL.Principal),
  'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UploadStoryRequest = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'contentType' : StoryContentType,
  'file' : ExternalBlob,
});
export const UploadVideoRequest = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'file' : ExternalBlob,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'addComment' : IDL.Func([IDL.Text, Comment], [], []),
  'adminCancelPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminDeleteStory' : IDL.Func([IDL.Text], [], []),
  'adminDeleteVideo' : IDL.Func([IDL.Text], [], []),
  'adminDownload' : IDL.Func([ExternalBlob], [], []),
  'adminGetAllPayments' : IDL.Func([], [IDL.Vec(PaymentTransaction)], []),
  'adminGetAllVideoCalls' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, Time, Time))],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canMessageUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'cleanupExpiredStories' : IDL.Func([], [IDL.Nat], []),
  'clearSignalingData' : IDL.Func([IDL.Text], [], []),
  'completePayment' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteOwnStory' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'dislikeReel' : IDL.Func([IDL.Text], [], []),
  'download' : IDL.Func([ExternalBlob], [], []),
  'failPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getActiveStoriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getAllActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getFriendRequestStatus' : IDL.Func(
      [IDL.Principal],
      [FriendRequestStatus],
      ['query'],
    ),
  'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFriendsWithProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getImageStoriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getOtherUsersActiveStories' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getOwnVideosAndStories' : IDL.Func(
      [],
      [IDL.Record({ 'stories' : IDL.Vec(Story), 'videos' : IDL.Vec(Video) })],
      ['query'],
    ),
  'getPaymentTransaction' : IDL.Func(
      [IDL.Text],
      [PaymentTransaction],
      ['query'],
    ),
  'getPushSubscription' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PushSubscription)],
      ['query'],
    ),
  'getReelStats' : IDL.Func([IDL.Text], [ReelStats], []),
  'getSignalingData' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SignalingEntryPublic)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalVideoCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserPaymentHistory' : IDL.Func(
      [],
      [IDL.Vec(PaymentTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVapidPublicKey' : IDL.Func([], [IDL.Text], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
  'getVideoCallHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, Time, Time))],
      ['query'],
    ),
  'getVideoStoriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getVideosByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
  'incrementViews' : IDL.Func([IDL.Text], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initiatePayment' : IDL.Func(
      [IDL.Principal, IDL.Nat, PaymentMethod],
      [IDL.Text],
      [],
    ),
  'initiateVideoCall' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeReel' : IDL.Func([IDL.Text], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'processPayment' : IDL.Func([IDL.Text], [], []),
  'recordVideoCall' : IDL.Func([IDL.Principal, Time, Time], [], []),
  'registerPushSubscription' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'removePushSubscription' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUserProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'searchUsers' : IDL.Func([IDL.Text], [SearchUsersResult], ['query']),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Vec(ExternalBlob))],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setVapidJwt' : IDL.Func([IDL.Text], [], []),
  'shareReel' : IDL.Func([IDL.Text], [], []),
  'startChatWithUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'storeSignalingData' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transferBetweenUsers' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProfileImage' : IDL.Func([ExternalBlob], [], []),
  'uploadAvatar' : IDL.Func([ExternalBlob], [IDL.Text], []),
  'uploadLogo' : IDL.Func([ExternalBlob], [], []),
  'uploadStory' : IDL.Func([UploadStoryRequest], [IDL.Text], []),
  'uploadVideo' : IDL.Func([UploadVideoRequest], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Comment = IDL.Record({ 'text' : IDL.Text, 'author' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Record({ 'provider' : IDL.Text }),
    'creditCard' : IDL.Null,
    'digitalWallet' : IDL.Record({ 'provider' : IDL.Text }),
    'debitCard' : IDL.Null,
    'netBanking' : IDL.Record({ 'bank' : IDL.Text }),
  });
  const Time = IDL.Int;
  const PaymentTransaction = IDL.Record({
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'failureReason' : IDL.Opt(IDL.Text),
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const StoryContentType = IDL.Variant({
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'contentType' : StoryContentType,
    'file' : ExternalBlob,
    'uploadTime' : Time,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'attachments' : IDL.Opt(IDL.Vec(ExternalBlob)),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'uploadTime' : Time,
  });
  const FriendRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PushSubscription = IDL.Record({
    'endpoint' : IDL.Text,
    'p256dhKey' : IDL.Text,
    'authKey' : IDL.Text,
  });
  const ReelStats = IDL.Record({
    'shares' : IDL.Nat,
    'views' : IDL.Nat,
    'likes' : IDL.Nat,
    'comments' : IDL.Vec(Comment),
    'dislikes' : IDL.Nat,
  });
  const SignalingEntryPublic = IDL.Record({
    'data' : IDL.Text,
    'sender' : IDL.Principal,
    'dataType' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const NotificationType = IDL.Variant({
    'paymentNotification' : IDL.Null,
    'videoCall' : IDL.Null,
    'friendRequestAccepted' : IDL.Null,
    'newMessage' : IDL.Null,
    'friendRequest' : IDL.Null,
  });
  const Notification = IDL.Record({
    'content' : IDL.Text,
    'notificationType' : NotificationType,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'senderName' : IDL.Text,
  });
  const FriendRequest = IDL.Record({
    'status' : FriendRequestStatus,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
  });
  const SearchUsersResult = IDL.Record({
    'pendingRequests' : IDL.Vec(FriendRequest),
    'friends' : IDL.Vec(IDL.Principal),
    'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UploadStoryRequest = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'contentType' : StoryContentType,
    'file' : ExternalBlob,
  });
  const UploadVideoRequest = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'file' : ExternalBlob,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'addComment' : IDL.Func([IDL.Text, Comment], [], []),
    'adminCancelPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminDeleteStory' : IDL.Func([IDL.Text], [], []),
    'adminDeleteVideo' : IDL.Func([IDL.Text], [], []),
    'adminDownload' : IDL.Func([ExternalBlob], [], []),
    'adminGetAllPayments' : IDL.Func([], [IDL.Vec(PaymentTransaction)], []),
    'adminGetAllVideoCalls' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, Time, Time))],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canMessageUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'cleanupExpiredStories' : IDL.Func([], [IDL.Nat], []),
    'clearSignalingData' : IDL.Func([IDL.Text], [], []),
    'completePayment' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteOwnStory' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'dislikeReel' : IDL.Func([IDL.Text], [], []),
    'download' : IDL.Func([ExternalBlob], [], []),
    'failPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getActiveStoriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getAllActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getFriendRequestStatus' : IDL.Func(
        [IDL.Principal],
        [FriendRequestStatus],
        ['query'],
      ),
    'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFriendsWithProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getImageStoriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOtherUsersActiveStories' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getOwnVideosAndStories' : IDL.Func(
        [],
        [IDL.Record({ 'stories' : IDL.Vec(Story), 'videos' : IDL.Vec(Video) })],
        ['query'],
      ),
    'getPaymentTransaction' : IDL.Func(
        [IDL.Text],
        [PaymentTransaction],
        ['query'],
      ),
    'getPushSubscription' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PushSubscription)],
        ['query'],
      ),
    'getReelStats' : IDL.Func([IDL.Text], [ReelStats], []),
    'getSignalingData' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SignalingEntryPublic)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalVideoCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserPaymentHistory' : IDL.Func(
        [],
        [IDL.Vec(PaymentTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVapidPublicKey' : IDL.Func([], [IDL.Text], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
    'getVideoCallHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, Time, Time))],
        ['query'],
      ),
    'getVideoStoriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getVideosByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'incrementViews' : IDL.Func([IDL.Text], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initiatePayment' : IDL.Func(
        [IDL.Principal, IDL.Nat, PaymentMethod],
        [IDL.Text],
        [],
      ),
    'initiateVideoCall' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeReel' : IDL.Func([IDL.Text], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'processPayment' : IDL.Func([IDL.Text], [], []),
    'recordVideoCall' : IDL.Func([IDL.Principal, Time, Time], [], []),
    'registerPushSubscription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'rejectFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'removePushSubscription' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUserProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'searchUsers' : IDL.Func([IDL.Text], [SearchUsersResult], ['query']),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Vec(ExternalBlob))],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setVapidJwt' : IDL.Func([IDL.Text], [], []),
    'shareReel' : IDL.Func([IDL.Text], [], []),
    'startChatWithUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'storeSignalingData' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transferBetweenUsers' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProfileImage' : IDL.Func([ExternalBlob], [], []),
    'uploadAvatar' : IDL.Func([ExternalBlob], [IDL.Text], []),
    'uploadLogo' : IDL.Func([ExternalBlob], [], []),
    'uploadStory' : IDL.Func([UploadStoryRequest], [IDL.Text], []),
    'uploadVideo' : IDL.Func([UploadVideoRequest], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };