/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment { 'text' : string, 'author' : string }
export type ExternalBlob = Uint8Array;
export interface FriendRequest {
  'status' : FriendRequestStatus,
  'recipient' : Principal,
  'sender' : Principal,
}
export type FriendRequestStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Message {
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'attachments' : [] | [Array<ExternalBlob>],
}
export interface Notification {
  'content' : string,
  'notificationType' : NotificationType,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : Time,
  'senderName' : string,
}
export type NotificationType = { 'paymentNotification' : null } |
  { 'videoCall' : null } |
  { 'friendRequestAccepted' : null } |
  { 'newMessage' : null } |
  { 'friendRequest' : null };
export type PaymentMethod = { 'upi' : { 'provider' : string } } |
  { 'creditCard' : null } |
  { 'digitalWallet' : { 'provider' : string } } |
  { 'debitCard' : null } |
  { 'netBanking' : { 'bank' : string } };
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface PaymentTransaction {
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'failureReason' : [] | [string],
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
  'transactionId' : string,
}
export interface PushSubscription {
  'endpoint' : string,
  'p256dhKey' : string,
  'authKey' : string,
}
export interface ReelStats {
  'shares' : bigint,
  'views' : bigint,
  'likes' : bigint,
  'comments' : Array<Comment>,
  'dislikes' : bigint,
}
export interface SearchUsersResult {
  'pendingRequests' : Array<FriendRequest>,
  'friends' : Array<Principal>,
  'profiles' : Array<[Principal, UserProfile]>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SignalingEntryPublic {
  'data' : string,
  'sender' : Principal,
  'dataType' : string,
}
export interface Story {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'thumbnail' : [] | [ExternalBlob],
  'contentType' : StoryContentType,
  'file' : ExternalBlob,
  'uploadTime' : Time,
}
export type StoryContentType = { 'video' : null } |
  { 'image' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UploadStoryRequest {
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'contentType' : StoryContentType,
  'file' : ExternalBlob,
}
export interface UploadVideoRequest {
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'file' : ExternalBlob,
  'description' : string,
}
export interface UserProfile {
  'bio' : [] | [string],
  'balance' : bigint,
  'name' : string,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'thumbnail' : [] | [ExternalBlob],
  'file' : ExternalBlob,
  'description' : string,
  'uploadTime' : Time,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addComment' : ActorMethod<[string, Comment], undefined>,
  'adminCancelPayment' : ActorMethod<[string, string], undefined>,
  'adminDeleteStory' : ActorMethod<[string], undefined>,
  'adminDeleteVideo' : ActorMethod<[string], undefined>,
  'adminDownload' : ActorMethod<[ExternalBlob], undefined>,
  'adminGetAllPayments' : ActorMethod<[], Array<PaymentTransaction>>,
  'adminGetAllVideoCalls' : ActorMethod<
    [],
    Array<[Principal, Principal, Time, Time]>
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canMessageUser' : ActorMethod<[Principal], boolean>,
  'cleanupExpiredStories' : ActorMethod<[], bigint>,
  'clearSignalingData' : ActorMethod<[string], undefined>,
  'completePayment' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteOwnStory' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'dislikeReel' : ActorMethod<[string], undefined>,
  'download' : ActorMethod<[ExternalBlob], undefined>,
  'failPayment' : ActorMethod<[string, string], undefined>,
  'getActiveStoriesByUser' : ActorMethod<[Principal], Array<Story>>,
  'getAllActiveStories' : ActorMethod<[], Array<Story>>,
  'getAllComments' : ActorMethod<[string], Array<Comment>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[], Array<Video>>,
  'getFriendRequestStatus' : ActorMethod<[Principal], FriendRequestStatus>,
  'getFriends' : ActorMethod<[], Array<Principal>>,
  'getFriendsWithProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getImageStoriesByUser' : ActorMethod<[Principal], Array<Story>>,
  'getLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getOtherUsersActiveStories' : ActorMethod<[Principal], Array<Story>>,
  'getOwnVideosAndStories' : ActorMethod<
    [],
    { 'stories' : Array<Story>, 'videos' : Array<Video> }
  >,
  'getPaymentTransaction' : ActorMethod<[string], PaymentTransaction>,
  'getPushSubscription' : ActorMethod<[Principal], [] | [PushSubscription]>,
  'getReelStats' : ActorMethod<[string], ReelStats>,
  'getSignalingData' : ActorMethod<[string], Array<SignalingEntryPublic>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalVideoCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserPaymentHistory' : ActorMethod<[], Array<PaymentTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVapidPublicKey' : ActorMethod<[], string>,
  'getVideo' : ActorMethod<[string], Video>,
  'getVideoCallHistory' : ActorMethod<
    [],
    Array<[Principal, Principal, Time, Time]>
  >,
  'getVideoStoriesByUser' : ActorMethod<[Principal], Array<Story>>,
  'getVideosByCreator' : ActorMethod<[Principal], Array<Video>>,
  'incrementViews' : ActorMethod<[string], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initiatePayment' : ActorMethod<[Principal, bigint, PaymentMethod], string>,
  'initiateVideoCall' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeReel' : ActorMethod<[string], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'processPayment' : ActorMethod<[string], undefined>,
  'recordVideoCall' : ActorMethod<[Principal, Time, Time], undefined>,
  'registerPushSubscription' : ActorMethod<[string, string, string], undefined>,
  'rejectFriendRequest' : ActorMethod<[Principal], undefined>,
  'removePushSubscription' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUserProfiles' : ActorMethod<[string], Array<[Principal, UserProfile]>>,
  'searchUsers' : ActorMethod<[string], SearchUsersResult>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<
    [Principal, string, [] | [Array<ExternalBlob>]],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setVapidJwt' : ActorMethod<[string], undefined>,
  'shareReel' : ActorMethod<[string], undefined>,
  'startChatWithUser' : ActorMethod<[Principal], string>,
  'storeSignalingData' : ActorMethod<[string, string, string], undefined>,
  'transferBetweenUsers' : ActorMethod<
    [Principal, Principal, bigint],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProfileImage' : ActorMethod<[ExternalBlob], undefined>,
  'uploadAvatar' : ActorMethod<[ExternalBlob], string>,
  'uploadLogo' : ActorMethod<[ExternalBlob], undefined>,
  'uploadStory' : ActorMethod<[UploadStoryRequest], string>,
  'uploadVideo' : ActorMethod<[UploadVideoRequest], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];