/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: string;
    title: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    file: ExternalBlob;
    description: string;
    uploadTime: Time;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface PushSubscription {
    endpoint: string;
    p256dhKey: string;
    authKey: string;
}
export type PaymentMethod = {
    __kind__: "upi";
    upi: {
        provider: string;
    };
} | {
    __kind__: "creditCard";
    creditCard: null;
} | {
    __kind__: "digitalWallet";
    digitalWallet: {
        provider: string;
    };
} | {
    __kind__: "debitCard";
    debitCard: null;
} | {
    __kind__: "netBanking";
    netBanking: {
        bank: string;
    };
};
export interface PaymentTransaction {
    status: PaymentStatus;
    paymentMethod: PaymentMethod;
    failureReason?: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
    amount: bigint;
    transactionId: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface FriendRequest {
    status: FriendRequestStatus;
    recipient: Principal;
    sender: Principal;
}
export interface ReelStats {
    shares: bigint;
    views: bigint;
    likes: bigint;
    comments: Array<Comment>;
    dislikes: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UploadVideoRequest {
    title: string;
    thumbnail?: ExternalBlob;
    file: ExternalBlob;
    description: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SearchUsersResult {
    pendingRequests: Array<FriendRequest>;
    friends: Array<Principal>;
    profiles: Array<[Principal, UserProfile]>;
}
export interface Comment {
    text: string;
    author: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Story {
    id: string;
    title: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    contentType: StoryContentType;
    file: ExternalBlob;
    uploadTime: Time;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface SignalingEntryPublic {
    data: string;
    sender: Principal;
    dataType: string;
}
export interface Notification {
    content: string;
    notificationType: NotificationType;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
    senderName: string;
}
export interface Message {
    content: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
    attachments?: Array<ExternalBlob>;
}
export interface UploadStoryRequest {
    title: string;
    thumbnail?: ExternalBlob;
    contentType: StoryContentType;
    file: ExternalBlob;
}
export interface UserProfile {
    bio?: string;
    balance: bigint;
    name: string;
    avatar?: ExternalBlob;
}
export enum FriendRequestStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum NotificationType {
    paymentNotification = "paymentNotification",
    videoCall = "videoCall",
    friendRequestAccepted = "friendRequestAccepted",
    newMessage = "newMessage",
    friendRequest = "friendRequest"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    processing = "processing",
    failed = "failed"
}
export enum StoryContentType {
    video = "video",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptFriendRequest(sender: Principal): Promise<void>;
    addComment(reelId: string, comment: Comment): Promise<void>;
    adminCancelPayment(transactionId: string, reason: string): Promise<void>;
    adminDeleteStory(storyId: string): Promise<void>;
    adminDeleteVideo(id: string): Promise<void>;
    adminDownload(blob: ExternalBlob): Promise<void>;
    adminGetAllPayments(): Promise<Array<PaymentTransaction>>;
    adminGetAllVideoCalls(): Promise<Array<[Principal, Principal, Time, Time]>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canMessageUser(targetUser: Principal): Promise<boolean>;
    cleanupExpiredStories(): Promise<bigint>;
    clearSignalingData(sessionId: string): Promise<void>;
    completePayment(transactionId: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteOwnStory(storyId: string): Promise<void>;
    deleteVideo(id: string): Promise<void>;
    dislikeReel(reelId: string): Promise<void>;
    download(blob: ExternalBlob): Promise<void>;
    failPayment(transactionId: string, reason: string): Promise<void>;
    getActiveStoriesByUser(user: Principal): Promise<Array<Story>>;
    getAllActiveStories(): Promise<Array<Story>>;
    getAllComments(reelId: string): Promise<Array<Comment>>;
    getAllMessages(): Promise<Array<Message>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getAllVideos(): Promise<Array<Video>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeed(): Promise<Array<Video>>;
    getFriendRequestStatus(otherUser: Principal): Promise<FriendRequestStatus>;
    getFriends(): Promise<Array<Principal>>;
    getFriendsWithProfiles(): Promise<Array<UserProfile>>;
    getImageStoriesByUser(user: Principal): Promise<Array<Story>>;
    getLogo(): Promise<ExternalBlob | null>;
    getMessagesWithUser(otherUser: Principal): Promise<Array<Message>>;
    getOtherUsersActiveStories(user: Principal): Promise<Array<Story>>;
    getOwnVideosAndStories(): Promise<{
        stories: Array<Story>;
        videos: Array<Video>;
    }>;
    getPaymentTransaction(transactionId: string): Promise<PaymentTransaction>;
    getPushSubscription(user: Principal): Promise<PushSubscription | null>;
    getReelStats(reelId: string): Promise<ReelStats>;
    getSignalingData(sessionId: string): Promise<Array<SignalingEntryPublic>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTotalVideoCount(): Promise<bigint>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserNotifications(): Promise<Array<Notification>>;
    getUserPaymentHistory(): Promise<Array<PaymentTransaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVapidPublicKey(): Promise<string>;
    getVideo(id: string): Promise<Video>;
    getVideoCallHistory(): Promise<Array<[Principal, Principal, Time, Time]>>;
    getVideoStoriesByUser(user: Principal): Promise<Array<Story>>;
    getVideosByCreator(creator: Principal): Promise<Array<Video>>;
    incrementViews(reelId: string): Promise<void>;
    initializeAccessControl(): Promise<void>;
    initiatePayment(recipient: Principal, amount: bigint, paymentMethod: PaymentMethod): Promise<string>;
    initiateVideoCall(receiver: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    likeReel(reelId: string): Promise<void>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    processPayment(transactionId: string): Promise<void>;
    recordVideoCall(receiver: Principal, startTime: Time, endTime: Time): Promise<void>;
    registerPushSubscription(endpoint: string, p256dhKey: string, authKey: string): Promise<void>;
    rejectFriendRequest(sender: Principal): Promise<void>;
    removePushSubscription(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchUserProfiles(searchTerm: string): Promise<Array<[Principal, UserProfile]>>;
    searchUsers(searchTerm: string): Promise<SearchUsersResult>;
    searchVideos(searchTerm: string): Promise<Array<Video>>;
    sendFriendRequest(recipient: Principal): Promise<void>;
    sendMessage(recipient: Principal, content: string, attachments: Array<ExternalBlob> | null): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setVapidJwt(jwt: string): Promise<void>;
    shareReel(reelId: string): Promise<void>;
    startChatWithUser(targetUser: Principal): Promise<string>;
    storeSignalingData(sessionId: string, dataType: string, data: string): Promise<void>;
    transferBetweenUsers(sender: Principal, recipient: Principal, amount: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateProfileImage(newAvatarFile: ExternalBlob): Promise<void>;
    uploadAvatar(file: ExternalBlob): Promise<string>;
    uploadLogo(file: ExternalBlob): Promise<void>;
    uploadStory(request: UploadStoryRequest): Promise<string>;
    uploadVideo(request: UploadVideoRequest): Promise<string>;
}
import type { ExternalBlob as _ExternalBlob, FriendRequest as _FriendRequest, FriendRequestStatus as _FriendRequestStatus, Message as _Message, Notification as _Notification, NotificationType as _NotificationType, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, PaymentTransaction as _PaymentTransaction, PushSubscription as _PushSubscription, SearchUsersResult as _SearchUsersResult, Story as _Story, StoryContentType as _StoryContentType, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UploadStoryRequest as _UploadStoryRequest, UploadVideoRequest as _UploadVideoRequest, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: Comment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async adminCancelPayment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCancelPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCancelPayment(arg0, arg1);
            return result;
        }
    }
    async adminDeleteStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteStory(arg0);
            return result;
        }
    }
    async adminDeleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteVideo(arg0);
            return result;
        }
    }
    async adminDownload(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDownload(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDownload(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminGetAllPayments(): Promise<Array<PaymentTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllPayments();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllPayments();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllVideoCalls(): Promise<Array<[Principal, Principal, Time, Time]>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllVideoCalls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllVideoCalls();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canMessageUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canMessageUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canMessageUser(arg0);
            return result;
        }
    }
    async cleanupExpiredStories(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupExpiredStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupExpiredStories();
            return result;
        }
    }
    async clearSignalingData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSignalingData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSignalingData(arg0);
            return result;
        }
    }
    async completePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePayment(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteOwnStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOwnStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOwnStory(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async dislikeReel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dislikeReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dislikeReel(arg0);
            return result;
        }
    }
    async download(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.download(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.download(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async failPayment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.failPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.failPayment(arg0, arg1);
            return result;
        }
    }
    async getActiveStoriesByUser(arg0: Principal): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStoriesByUser(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStoriesByUser(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveStories();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveStories();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComments(arg0);
            return result;
        }
    }
    async getAllMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeed(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendRequestStatus(arg0: Principal): Promise<FriendRequestStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequestStatus(arg0);
                return from_candid_FriendRequestStatus_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequestStatus(arg0);
            return from_candid_FriendRequestStatus_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriends(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getFriendsWithProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsWithProfiles();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsWithProfiles();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImageStoriesByUser(arg0: Principal): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImageStoriesByUser(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImageStoriesByUser(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogo(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogo();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogo();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesWithUser(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesWithUser(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesWithUser(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOtherUsersActiveStories(arg0: Principal): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOtherUsersActiveStories(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOtherUsersActiveStories(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnVideosAndStories(): Promise<{
        stories: Array<Story>;
        videos: Array<Video>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnVideosAndStories();
                return from_candid_record_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnVideosAndStories();
            return from_candid_record_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentTransaction(arg0: string): Promise<PaymentTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentTransaction(arg0);
                return from_candid_PaymentTransaction_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentTransaction(arg0);
            return from_candid_PaymentTransaction_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPushSubscription(arg0: Principal): Promise<PushSubscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPushSubscription(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPushSubscription(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReelStats(arg0: string): Promise<ReelStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelStats(arg0);
            return result;
        }
    }
    async getSignalingData(arg0: string): Promise<Array<SignalingEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalingData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalingData(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalVideoCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVideoCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVideoCount();
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotifications();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotifications();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPaymentHistory(): Promise<Array<PaymentTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPaymentHistory();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPaymentHistory();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVapidPublicKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getVapidPublicKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVapidPublicKey();
            return result;
        }
    }
    async getVideo(arg0: string): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_Video_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_Video_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoCallHistory(): Promise<Array<[Principal, Principal, Time, Time]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoCallHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoCallHistory();
            return result;
        }
    }
    async getVideoStoriesByUser(arg0: Principal): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoStoriesByUser(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoStoriesByUser(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCreator(arg0: Principal): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCreator(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCreator(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementViews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViews(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initiatePayment(arg0: Principal, arg1: bigint, arg2: PaymentMethod): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initiatePayment(arg0, arg1, to_candid_PaymentMethod_n54(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiatePayment(arg0, arg1, to_candid_PaymentMethod_n54(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async initiateVideoCall(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateVideoCall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateVideoCall(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async likeReel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeReel(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async processPayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPayment(arg0);
            return result;
        }
    }
    async recordVideoCall(arg0: Principal, arg1: Time, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVideoCall(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVideoCall(arg0, arg1, arg2);
            return result;
        }
    }
    async registerPushSubscription(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPushSubscription(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPushSubscription(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFriendRequest(arg0);
            return result;
        }
    }
    async removePushSubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePushSubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePushSubscription();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchUserProfiles(arg0: string): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUserProfiles(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUserProfiles(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string): Promise<SearchUsersResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_SearchUsersResult_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_SearchUsersResult_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchVideos(arg0: string): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: Array<ExternalBlob> | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, await to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, await to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setVapidJwt(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVapidJwt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVapidJwt(arg0);
            return result;
        }
    }
    async shareReel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareReel(arg0);
            return result;
        }
    }
    async startChatWithUser(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startChatWithUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startChatWithUser(arg0);
            return result;
        }
    }
    async storeSignalingData(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeSignalingData(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeSignalingData(arg0, arg1, arg2);
            return result;
        }
    }
    async transferBetweenUsers(arg0: Principal, arg1: Principal, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferBetweenUsers(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferBetweenUsers(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateProfileImage(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileImage(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileImage(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadAvatar(arg0: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAvatar(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAvatar(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadLogo(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadLogo(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadLogo(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadStory(arg0: UploadStoryRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadStory(await to_candid_UploadStoryRequest_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadStory(await to_candid_UploadStoryRequest_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadVideo(arg0: UploadVideoRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(await to_candid_UploadVideoRequest_n69(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(await to_candid_UploadVideoRequest_n69(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FriendRequestStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequestStatus): FriendRequestStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRequest_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequest): FriendRequest {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
async function from_candid_Message_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Promise<Message> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentTransaction_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentTransaction): PaymentTransaction {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_SearchUsersResult_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchUsersResult): Promise<SearchUsersResult> {
    return await from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_StoryContentType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryContentType): StoryContentType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_Story_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Promise<Story> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ExternalBlob>]): Promise<Array<ExternalBlob> | null> {
    return value.length === 0 ? null : await from_candid_vec_n30(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PushSubscription]): PushSubscription | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    paymentMethod: _PaymentMethod;
    failureReason: [] | [string];
    recipient: Principal;
    sender: Principal;
    timestamp: _Time;
    amount: bigint;
    transactionId: string;
}): {
    status: PaymentStatus;
    paymentMethod: PaymentMethod;
    failureReason?: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
    amount: bigint;
    transactionId: string;
} {
    return {
        status: from_candid_PaymentStatus_n12(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n14(_uploadFile, _downloadFile, value.paymentMethod),
        failureReason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.failureReason)),
        recipient: value.recipient,
        sender: value.sender,
        timestamp: value.timestamp,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: Principal;
    thumbnail: [] | [_ExternalBlob];
    contentType: _StoryContentType;
    file: _ExternalBlob;
    uploadTime: _Time;
}): Promise<{
    id: string;
    title: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    contentType: StoryContentType;
    file: ExternalBlob;
    uploadTime: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.thumbnail)),
        contentType: from_candid_StoryContentType_n24(_uploadFile, _downloadFile, value.contentType),
        file: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.file),
        uploadTime: value.uploadTime
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    recipient: Principal;
    sender: Principal;
    timestamp: _Time;
    attachments: [] | [Array<_ExternalBlob>];
}): Promise<{
    content: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
    attachments?: Array<ExternalBlob>;
}> {
    return {
        content: value.content,
        recipient: value.recipient,
        sender: value.sender,
        timestamp: value.timestamp,
        attachments: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.attachments))
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    balance: bigint;
    name: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    bio?: string;
    balance: bigint;
    name: string;
    avatar?: ExternalBlob;
}> {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.bio)),
        balance: value.balance,
        name: value.name,
        avatar: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: Principal;
    thumbnail: [] | [_ExternalBlob];
    file: _ExternalBlob;
    description: string;
    uploadTime: _Time;
}): Promise<{
    id: string;
    title: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    file: ExternalBlob;
    description: string;
    uploadTime: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.thumbnail)),
        file: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.file),
        description: value.description,
        uploadTime: value.uploadTime
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stories: Array<_Story>;
    videos: Array<_Video>;
}): Promise<{
    stories: Array<Story>;
    videos: Array<Video>;
}> {
    return {
        stories: await from_candid_vec_n19(_uploadFile, _downloadFile, value.stories),
        videos: await from_candid_vec_n35(_uploadFile, _downloadFile, value.videos)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    notificationType: _NotificationType;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: _Time;
    senderName: string;
}): {
    content: string;
    notificationType: NotificationType;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
    senderName: string;
} {
    return {
        content: value.content,
        notificationType: from_candid_NotificationType_n52(_uploadFile, _downloadFile, value.notificationType),
        recipient: value.recipient,
        isRead: value.isRead,
        sender: value.sender,
        timestamp: value.timestamp,
        senderName: value.senderName
    };
}
async function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingRequests: Array<_FriendRequest>;
    friends: Array<Principal>;
    profiles: Array<[Principal, _UserProfile]>;
}): Promise<{
    pendingRequests: Array<FriendRequest>;
    friends: Array<Principal>;
    profiles: Array<[Principal, UserProfile]>;
}> {
    return {
        pendingRequests: from_candid_vec_n60(_uploadFile, _downloadFile, value.pendingRequests),
        friends: value.friends,
        profiles: await from_candid_vec_n31(_uploadFile, _downloadFile, value.profiles)
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FriendRequestStatus;
    recipient: Principal;
    sender: Principal;
}): {
    status: FriendRequestStatus;
    recipient: Principal;
    sender: Principal;
} {
    return {
        status: from_candid_FriendRequestStatus_n41(_uploadFile, _downloadFile, value.status),
        recipient: value.recipient,
        sender: value.sender
    };
}
async function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): Promise<[Principal, UserProfile]> {
    return [
        value[0],
        await from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "processing" in value ? PaymentStatus.processing : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: {
        provider: string;
    };
} | {
    creditCard: null;
} | {
    digitalWallet: {
        provider: string;
    };
} | {
    debitCard: null;
} | {
    netBanking: {
        bank: string;
    };
}): {
    __kind__: "upi";
    upi: {
        provider: string;
    };
} | {
    __kind__: "creditCard";
    creditCard: null;
} | {
    __kind__: "digitalWallet";
    digitalWallet: {
        provider: string;
    };
} | {
    __kind__: "debitCard";
    debitCard: null;
} | {
    __kind__: "netBanking";
    netBanking: {
        bank: string;
    };
} {
    return "upi" in value ? {
        __kind__: "upi",
        upi: value.upi
    } : "creditCard" in value ? {
        __kind__: "creditCard",
        creditCard: value.creditCard
    } : "digitalWallet" in value ? {
        __kind__: "digitalWallet",
        digitalWallet: value.digitalWallet
    } : "debitCard" in value ? {
        __kind__: "debitCard",
        debitCard: value.debitCard
    } : "netBanking" in value ? {
        __kind__: "netBanking",
        netBanking: value.netBanking
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): StoryContentType {
    return "video" in value ? StoryContentType.video : "image" in value ? StoryContentType.image : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): FriendRequestStatus {
    return "pending" in value ? FriendRequestStatus.pending : "rejected" in value ? FriendRequestStatus.rejected : "accepted" in value ? FriendRequestStatus.accepted : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentNotification: null;
} | {
    videoCall: null;
} | {
    friendRequestAccepted: null;
} | {
    newMessage: null;
} | {
    friendRequest: null;
}): NotificationType {
    return "paymentNotification" in value ? NotificationType.paymentNotification : "videoCall" in value ? NotificationType.videoCall : "friendRequestAccepted" in value ? NotificationType.friendRequestAccepted : "newMessage" in value ? NotificationType.newMessage : "friendRequest" in value ? NotificationType.friendRequest : value;
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Promise<Array<Story>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Story_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Promise<Array<Message>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Message_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Promise<Array<[Principal, UserProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n36(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRequest>): Array<FriendRequest> {
    return value.map((x)=>from_candid_FriendRequest_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentTransaction>): Array<PaymentTransaction> {
    return value.map((x)=>from_candid_PaymentTransaction_n10(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentMethod_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_StoryContentType_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoryContentType): _StoryContentType {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
async function to_candid_UploadStoryRequest_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadStoryRequest): Promise<_UploadStoryRequest> {
    return await to_candid_record_n66(_uploadFile, _downloadFile, value);
}
async function to_candid_UploadVideoRequest_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadVideoRequest): Promise<_UploadVideoRequest> {
    return await to_candid_record_n70(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob> | null): Promise<[] | [Array<_ExternalBlob>]> {
    return value === null ? candid_none() : candid_some(await to_candid_vec_n64(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    balance: bigint;
    name: string;
    avatar?: ExternalBlob;
}): Promise<{
    bio: [] | [string];
    balance: bigint;
    name: string;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        balance: value.balance,
        name: value.name,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
async function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnail?: ExternalBlob;
    contentType: StoryContentType;
    file: ExternalBlob;
}): Promise<{
    title: string;
    thumbnail: [] | [_ExternalBlob];
    contentType: _StoryContentType;
    file: _ExternalBlob;
}> {
    return {
        title: value.title,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        contentType: to_candid_StoryContentType_n67(_uploadFile, _downloadFile, value.contentType),
        file: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.file)
    };
}
async function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnail?: ExternalBlob;
    file: ExternalBlob;
    description: string;
}): Promise<{
    title: string;
    thumbnail: [] | [_ExternalBlob];
    file: _ExternalBlob;
    description: string;
}> {
    return {
        title: value.title,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        file: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.file),
        description: value.description
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "upi";
    upi: {
        provider: string;
    };
} | {
    __kind__: "creditCard";
    creditCard: null;
} | {
    __kind__: "digitalWallet";
    digitalWallet: {
        provider: string;
    };
} | {
    __kind__: "debitCard";
    debitCard: null;
} | {
    __kind__: "netBanking";
    netBanking: {
        bank: string;
    };
}): {
    upi: {
        provider: string;
    };
} | {
    creditCard: null;
} | {
    digitalWallet: {
        provider: string;
    };
} | {
    debitCard: null;
} | {
    netBanking: {
        bank: string;
    };
} {
    return value.__kind__ === "upi" ? {
        upi: value.upi
    } : value.__kind__ === "creditCard" ? {
        creditCard: value.creditCard
    } : value.__kind__ === "digitalWallet" ? {
        digitalWallet: value.digitalWallet
    } : value.__kind__ === "debitCard" ? {
        debitCard: value.debitCard
    } : value.__kind__ === "netBanking" ? {
        netBanking: value.netBanking
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoryContentType): {
    video: null;
} | {
    image: null;
} {
    return value == StoryContentType.video ? {
        video: null
    } : value == StoryContentType.image ? {
        image: null
    } : value;
}
async function to_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
