export const Strings = {
  welcome: {
    tapToStart: "Tap anywhere to start with sound",
    loading: "Loading...",
    logoAlt: "SOCIONET",
    voiceError: "Voice audio play failed:",
    bgmError: "BGM play failed:",
  },
  feed: {
    title: "Feed",
    premiumNetwork: "Premium Decentralized Network",
    uploadVideo: "Upload video",
    notifications: "Notifications",
    yourStory: "Your Story",
    emptyTitle: "Your feed is empty",
    emptyDesc: "Upload your first video and start building your royal audience. Everything you share appears here.",
    btnUpload: "Upload a Video",
    btnAddStory: "✨ Add a Story",
  },
  login: {
    failed: "Login failed. Please try again.",
    nextGenNetwork: "Next-Gen Decentralized Network",
    poweredBy: "✦ Powered by Blockchain",
    connecting: "Connecting to Blockchain…",
    continue: "Continue with Internet Identity",
    secured: "Secured",
    noPassword: "No Password",
    decentralized: "Decentralized",
    securedDesc: "Secured by Internet Computer blockchain.",
    manifesto: "No passwords. No data collection. Pure decentralization.",
    tapHint: "Tap above to enter the decentralized social network",
  },
  explore: {
    title: "Explore",
    discover: "Discover trending royal content",
    liveSearch: "Live Search",
    searchPlaceholder: "Search videos, people...",
    tabVideos: "Videos",
    tabPeople: "People",
    trending: "Trending",
    forYou: "For You",
    videosCount: "videos",
    noVideos: "No videos yet",
    emptyDesc: "Upload your first reel and be the first to appear in Explore.",
    btnUploadReel: "Upload a Reel",
    resultsFor: "Results for",
    noResults: "No results found",
    tryDifferentSearch: "Try a different search term",
    you: "You",
    following: "Following",
    message: "Message",
    sent: "Sent",
    follow: "Follow",
    noPeople: "No people found",
    tryDifferentName: "Try a different name",
  },
  reels: {
    title: "Reels",
    goBack: "Go back",
    uploadReel: "Upload reel",
    emptyTitle: "No Reels Yet",
    emptyDesc: "Be the first to share a reel! Upload a short video and let the world see your creativity.",
    btnFirstReel: "Upload Your First Reel",
  },
  messages: {
    loading: "Loading messages…",
    defaultUser: "User",
    now: "now",
    tapToChat: "Tap to chat ✨",
    activeNow: "Active now",
    startConversation: "Start the conversation",
    sayHiTo: (name: string) => `Say hi to ${name}! 👋`,
    attachment: "📎 Attachment",
    inputPlaceholder: "Message…",
    encoding: "Encoding attachment…",
    saving: "Saving to server…",
    complete: "Complete!",
    title: "Messages",
    searchPlaceholder: "Search people…",
    tabChats: "Chats",
    tabRequests: "Requests",
    friendRequests: "Friend Requests",
    people: "People",
    noUsersFound: (query: string) => `No users found for "${query}"`,
    noPendingRequests: "No pending requests",
    requestsDesc: "Friend requests will appear here.",
    quickMessage: "Quick Message",
    tapToStartChatting: "Tap to start chatting",
    noMessagesYet: "No messages yet",
    noMessagesDesc: "Search for people above and send a friend request to start chatting.",
    wantsToConnect: "Wants to connect",
    sent: "Sent",
    add: "Add",
    message: "Message",
    document: "Document",
    tapToDownload: "Tap to download",
    unknownUser: "Unknown User",
  },
  profile: {
    title: "Profile",
    back: "← Back",
    settings: "Settings",
    signOut: "Sign out",
    posts: "Posts",
    stories: "Stories",
    followers: "Followers",
    following: "Following",
    shareProfile: "Share Profile",
    shareTitle: "Profile",
    postsEmptyTitle: "Share Photos and Videos",
    postsEmptyDesc: "When you share photos and videos, they'll appear here.",
    reelsEmptyTitle: "No Reels Yet",
    reelsEmptyDesc: "Your reels will appear here once you create some.",
    taggedEmptyTitle: "No Tagged Posts",
    taggedEmptyDesc: "Photos and videos you're tagged in will appear here.",
  },
  auth: {
    loginSuccess: "Login successful, principal:",
  }
};
